name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 * * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: zanderlewis/waka-box-remastered@v0.1.2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c04a38ba711de5c27c7fab6951caf70d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
